import { useState } from 'react'
import { createHttpExplanationApi, type ArtworkExplanation as Explanation, type ExplanationApi } from '../services/explanationApi'
type State = { kind: 'idle' } | { kind: 'loading' } | { kind: 'success'; result: Explanation } | { kind: 'error' }
interface Props { publicId: string; api?: ExplanationApi }
const defaultApi = createHttpExplanationApi()
export function ArtworkExplanation({ publicId, api = defaultApi }: Props) {
  const [state, setState] = useState<State>({ kind: 'idle' })
  async function explain() { setState({ kind: 'loading' }); try { setState({ kind: 'success', result: await api.explainArtwork(publicId) }) } catch { setState({ kind: 'error' }) } }
  return <section className="explanation-panel" aria-labelledby="explanation-title"><p className="signal-label">Grounded AI / optional</p><h2 id="explanation-title">Look closer, without losing the evidence trail.</h2><p>The approved remote image and the museum facts shown above are the only inputs sent to AI.</p><button className="explain-button" type="button" onClick={explain} disabled={state.kind === 'loading'} aria-describedby="explanation-privacy">{state.kind === 'loading' ? 'Explaining artwork…' : 'Explain this artwork'}</button><p id="explanation-privacy" className="explanation-privacy">No image bytes are downloaded, cached, or stored by AI Aion.</p><div aria-live="polite" aria-busy={state.kind === 'loading'}>{state.kind === 'loading' && <p className="explanation-state">Creating a grounded explanation…</p>}{state.kind === 'error' && <div className="explanation-state error" role="alert"><h3>Explanation unavailable.</h3><p>The backend could not complete this request. Try again later.</p></div>}{state.kind === 'success' && <ExplanationResult result={state.result} />}</div></section>
}
function ExplanationResult({ result }: { result: Explanation }) {
  if (result.status === 'not_configured') return <div className="explanation-state"><h3>AI explanation is not configured.</h3><p>{result.message}</p></div>
  const generated = result.generated; if (!generated) return null
  return <article className="explanation-result"><p className="ai-label">AI-generated</p>{result.status === 'insufficient_context' && <div className="insufficient" role="status"><strong>Insufficient verified context</strong><p>The explanation is intentionally limited rather than guessing.</p></div>}<h3>Explanation</h3><p>{generated.summary}</p><h3>Verified museum facts</h3><dl>{result.verified_museum_facts.map((fact) => <div key={fact.label}><dt>{fact.label}</dt><dd>{fact.value}</dd></div>)}</dl><h3>Visual observations</h3>{generated.visual_observations.length ? <ul>{generated.visual_observations.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No reliable visual observations were returned.</p>}<h3>Possible interpretations</h3>{generated.inferences.length ? <ul>{generated.inferences.map((item) => <li key={item}>{item}</li>)}</ul> : <p>No interpretation is offered without stronger context.</p>}<h3>Uncertainty</h3><p>{generated.uncertainty}</p><p className="rights-notice">{result.rights_notice}</p><div className="ai-evidence-links"><a href={result.provenance.source_url} target="_blank" rel="noreferrer">Cleveland source ↗</a><a href={result.provenance.license.evidence_url} target="_blank" rel="noreferrer">Rights evidence ↗</a><a href={result.provenance.license.license_uri} target="_blank" rel="noreferrer">Exact CC0 license ↗</a></div></article>
}
